### ISSUE TITLE
Please add support for `copy run start`

### ISSUE THREAD

**Issue by mobig** [CiscoDevNet/terraform-provider-nxos#216]
The NXOS provider currently lacks a resource for saving the running configuration to startup, similar to the `iosxe_save_config` resource available for the IOSXE provider. Is it possible to incorporate this feature into the NXOS provider as well? 

For reference, the Cisco DevNet API documentation outlines this functionality:
[Copy Running Config to Startup Config](https://developer.cisco.com/docs/nx-os-n3k-n9k-api-ref-7-x/#!copy-running-config-startup-config/copy-running-config-startup-config)
I've successfully tested this API endpoint on a 9000v running version 9.3(9), and it works as expected.

For comparison, here is the resource for the IOSXE provider:
[iosxe_save_config Resource](https://registry.terraform.io/providers/CiscoDevNet/iosxe/latest/docs/resources/save_config)

Also, I want to express my gratitude for your continuous support for this and the other DevNet Terraform providers.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-nxos/commit/6f2c4153baefcb9721afd42c58cf2dc927ef4777

**Comment by danischm** [comment]
Added in v0.5.2 release.
