### ISSUE TITLE
Missing resources in generic bgp configuration

### ISSUE THREAD

**Issue by StevenHolm** [CiscoDevNet/terraform-provider-nxos#228]
### Usecase
I've been looking into deploying some nexus switching using terraform as the orchestration tool.
I found the following resources were missing from the available resources

### Ability to set local as on bgp peer 
```
resource "nxos_rest" "bgp_localas" {
    for_each = local.bgp_neighbor
    dn = "sys/bgp/inst/dom-[${nxos_bgp_address_family.address_family.vrf}]/peer-[${nxos_bgp_peer.peer[each.key].address}]/localasn"
    class_name = "bgpLocalAsn"
    content = {
      localAsn = each.value.local_as
    }
}
```

### Ability to set BFD, TTL (eBGP multihop) and password og bgp peer
```
resource "nxos_rest" "system_interface_default_shutdown" {
    for_each = local.bgp_neighbor
    dn = "sys/bgp/inst/dom-[${nxos_bgp_address_family.address_family.vrf}]/peer-[${nxos_bgp_peer.peer[each.key].address}]"
    class_name = "bgpPeer"
    content  = {
      passwdType = 0
      password = each.value.password
      ctrl = each.value.bfd
      ttl = each.value.ebgp_multihop 
    }
}
```
The password seems to be returned in the encrypted state - is there a way to encrypt the password prior to deploying it? and then in turn deploy it using passwdType 3?

### Ability to set passive-interface default and bfd on ospf instance
```
resource "nxos_rest" "ospf_ctrl" {
    for_each = local.bgp_neighbor
    dn = "sys/ospf/inst-${var.ospf_name}/dom-${nxos_ospf_vrf.vrf.name}"
    class_name = "ospfDom"
    content = {
      ctrl = 5
    }
}
```
### General security, ability to change the default state of physical ports
```
resource "nxos_rest" "system_interface_default_shutdown" {
    dn = "sys/ethpm/inst"
    class_name = "ethpmInst"
    content = {
      systemDefaultAdminSt = "down"
    }

}

```

**Comment by alxgarder** [comment]
+1

**Comment by Nije-PCH** [comment]
+1

**Comment by moskrive** [comment]
As the configuration of a BGP password using a unencrypted password returns the encrypted version of the password is it required to add the following lifecycle statement to the nxos_bgp_peer resource.

lifecycle {
  ignore_changes = [
    password_type
  ]
}

This instructs Terraform to ignore that the desired value is not identical to the one returned by the Nexus device
