### ISSUE TITLE
Version 0.5.3 dont save the running-conifg to startup config

### ISSUE THREAD

**Issue by hani010** [CiscoDevNet/terraform-provider-nxos#243]
Hi,
I noticed that version 05.3 no longer saves the running conifg into the startup config, could you fix that. 
With version 0.5.2 works it fine.
Regards

**Comment by danischm** [comment]
Nothing has changed with regards to that. In fact we are not modifying the "running config", as we are making changes to the DME model directly.

**Comment by hani010** [comment]
We had an reboot from a switch, the changes that were have made before were no longer there after the reboot. For testing i created a vlan with version 0.5.2 and 0.5.3. With version 0.5.2 the vlan was written into the startup-config, unfortunately not with version 0.5.3. I haven't checked the DME configuration

**Comment by hani010** [comment]
i have add the resource "nxos_save_config" to my terraform environment and works fine.. . We can close the issue

**Comment by danischm** [comment]
A `nxos_save_config` resource does not exist for NX-OS. Are you referring to the IOS-XE provider maybe?

**Comment by hani010** [comment]
look here for the NX-OS rescource: 
https://registry.terraform.io/providers/CiscoDevNet/nxos/latest/docs/resources/save_config

**Comment by danischm** [comment]
I am sorry, you are right. Got confused myself. :)

**Comment by danischm** [comment]
And yes, you need to "execute/create" that resource at the end to persist the config.
