### ISSUE TITLE
After removing resource cdp/lldp config left on interface

### ISSUE THREAD

**Issue by krzysztofmaciejewskiit** [CiscoDevNet/terraform-provider-nxos#268]
When I delete a part of the code in e.g. part two, responsible for cdp or lldp it says it is destroyed, but it stays on the Nexus configuration and I don't know why all other things get deleted and those 3 lines of code (seen on the switch) stay, even though the terraform logs clearly say "destroyed". My removal is to simply remove the part of the code responsible for adding cdp and lldp to the second interface, that is, everything from that tag down:
//============================================== part-2 ==============================================

![image](https://github.com/user-attachments/assets/222069e2-cf36-4975-9a3f-aca4bb12b8dd)
![image](https://github.com/user-attachments/assets/c33b0ca0-2a5f-4ef7-800d-ebc57d53b529)
![image](https://github.com/user-attachments/assets/0fc4fe8b-d214-489f-917c-c721f16bafdd)

Code from terraform: main.tf
```
terraform {
  required_providers {
    nxos = {
      source  = "CiscoDevNet/nxos"
      version = "0.5.3"
    }
  }
}

provider "nxos" {
  username = var.nxos_username
  password = var.nxos_password
  url      = var.nxos_url
}

/*============================================ common ============================================*/

resource "nxos_feature_lldp" "lldp" {
  admin_state = "enabled"
}

/*=====================================*/

resource "nxos_rest" "cdpEntity" {
  dn         = "sys/cdp"
  class_name = "cdpEntity"
}

//============================================== part-1 ==============================================
//============================================== part-1 ==============================================
//============================================== part-1 ==============================================

/*============================================ description & L3 ============================================*/

resource "nxos_physical_interface" "desc-L3" {
  interface_id = "eth1/5"
  description  = "desc1"
  layer = "Layer3"
  admin_state  = "up"
  user_configured_flags = "admin_state"
}

/*============================================ lldp ============================================*/

resource "nxos_rest" "lldpInst" {
  depends_on = [nxos_feature_lldp.lldp]
  dn         = "sys/lldp/inst"
  class_name = "lldpInst"
  children = [
    {
      rn         = "if-[eth1/5]"
      class_name = "lldpIf"
      content = {
        adminRxSt = "disabled",
        adminTxSt = "disabled",
        id        = "eth1/5"
      }
    }
  ]
}

/*============================================ cdp ============================================*/

resource "nxos_rest" "cdpInst" {
  depends_on = [nxos_rest.cdpEntity]
  dn         = "sys/cdp/inst"
  class_name = "cdpInst"
  children = [
    {
      rn         = "if-[eth1/5]"
      class_name = "cdpIf"
      content = {
        adminSt = "disabled",
        id        = "eth1/5"
      }
    }
  ]
}

//============================================== part-2 ==============================================
//============================================== part-2 ==============================================
//============================================== part-2 ==============================================

/*============================================ description & L3 ============================================*/

resource "nxos_physical_interface" "desc-L3v2" {
  interface_id = "eth1/6"
  description = "desc2"
  layer = "Layer3"
  admin_state  = "up"
  user_configured_flags = "admin_state"
}

/*============================================ lldp ============================================*/

resource "nxos_rest" "lldpInstv2" {
  depends_on = [nxos_feature_lldp.lldp]
  dn         = "sys/lldp/inst"
  class_name = "lldpInst"
  children = [
    {
      rn         = "if-[eth1/6]"
      class_name = "lldpIf"
      content = {
        adminRxSt = "disabled",
        adminTxSt = "disabled",
        id        = "eth1/6"
      }
    }
  ]
}

/*============================================ cdp ============================================*/

resource "nxos_rest" "cdpInstv2" {
  depends_on = [nxos_rest.cdpEntity]
  dn         = "sys/cdp/inst"
  class_name = "cdpInst"
  children = [
    {
      rn         = "if-[eth1/6]"
      class_name = "cdpIf"
      content = {
        adminSt = "disabled",
        id        = "eth1/6"
      }
    }
  ]
}
```

Link to Cisco Community discussion: https://community.cisco.com/t5/devnet-general-discussions/terraform-after-removing-resource-cdp-lldp-config-left-on/td-p/5157851

**Comment by danischm** [comment]
There is no need to manage the "sys/lldp/inst" and "sys/cdp/inst" objects using Terraform. These are system level objects that already exist and therefore there is no need to manage them using Terraform. What happens here is, TF attempts to delete those system objects (which would implicitly also delete the child objects), but it fails as those types of objects cannot be deleted and therefore the child objects remain in place as well. The "nxos_rest" resource silently suppresses this error, because it is a generic resource and in some cases this is expected. The resources should therefore be defined like this:

```terraform
resource "nxos_rest" "lldpIf" {
  depends_on = [nxos_feature_lldp.lldp]
  dn         = "sys/lldp/inst/if-[eth1/5]"
  class_name = "lldpIf"
  content = {
    adminRxSt = "disabled"
    adminTxSt = "disabled"
    id        = "eth1/5"
  }
}

resource "nxos_rest" "cdpIf" {
  depends_on = [nxos_rest.cdpEntity]
  dn         = "sys/cdp/inst/if-[eth1/5]"
  class_name = "cdpIf"
  content = {
    adminSt = "disabled"
    id        = "eth1/5"
  }
}
```

**Comment by krzysztofmaciejewskiit** [comment]
This is my code. What you propose does not work.
This is a very reduced version of my code. It configures the following interfaces and on each one I want to enter 
```
  no lldp transmit
  no lldp receive
  no cdp enable
```
so here globally I want to ‘enable’ cdp and lldp. 

```
resource "nxos_feature_lldp" "lldp" {
  admin_state = "enabled"
}

resource "nxos_rest" "cdpEntity" {
  dn         = "sys/cdp"
  class_name = "cdpEntity"
}
```

Then on each subsequent interface I want to use ‘depends on’ for this base ‘enable cdp and lldp’. If it ever comes to the need to remove an interface from my code so that I throw the configuration on it then I will simply remove the part of the code in Terraform that previously allowed it to be configured. I would then expect the commands (no lldp transmit, no lldp receive, no cdp enable) would be removed, but this does not happen.

Even after removing this part, my interface looks like this:
```
interface Ethernet1/3
  no lldp transmit
  no lldp receive
  no cdp enable
```

My entire code:
```
terraform {
  required_providers {
    nxos = {
      source  = "CiscoDevNet/nxos"
      version = "0.5.5"
    }
  }
}

provider "nxos" {
  username = var.nxos_username
  password = var.nxos_password
  url      = var.nxos_url
}

/*============================================ COMMON ============================================*/

resource "nxos_feature_lldp" "lldp" {
  admin_state = "enabled"
}

resource "nxos_rest" "cdpEntity" {
  dn         = "sys/cdp"
  class_name = "cdpEntity"
}

/*============================================ LLDP ============================================*/

resource "nxos_rest" "lldpIf" {
  dn         = "sys/lldp/inst/if-[${var.interface}]"
  class_name = "lldpIf"
  content     = {
    adminRxSt = "disabled",
    adminTxSt = "disabled",
    id        = var.interface
  }
}

/*============================================ CDP ============================================*/

resource "nxos_rest" "cdpIf" {
  dn         = "sys/cdp/inst/if-[${var.interface}]"
  class_name = "cdpIf"
    content  = {
    adminSt  = "disabled",
    id       = var.interface
  }
}
```

I would expect that when my whole code looks like this (after removing the interface configuration):
```
terraform {
  required_providers {
    nxos = {
      source  = "CiscoDevNet/nxos"
      version = "0.5.5"
    }
  }
}

provider "nxos" {
  username = var.nxos_username
  password = var.nxos_password
  url      = var.nxos_url
}

/*============================================ COMMON ============================================*/

resource "nxos_feature_lldp" "lldp" {
  admin_state = "enabled"
}

resource "nxos_rest" "cdpEntity" {
  dn         = "sys/cdp"
  class_name = "cdpEntity"
}
```

This would then on the interface on the switch also be cleared of all configuration, and as I say, acct this configuration remains.

**Comment by danischm** [comment]
The `cdpIf` object cannot be deleted and therefore the configuration does not get removed on the CLI either. You can verify that by enabling debug logging where you can see the following message:
```
[DEBUG] HTTP Response: {"imdata":[{"error": {"attributes": {"code": "107","text": "Cannot delete object of class:cdpIf"}}}]}
```
This is how the DME model behaves and there is nothing really we can do on the Terraform side.

**Comment by krzysztofmaciejewskiit** [comment]
Why can I add via terraform ‘no cdp enable’ but cannot withdraw this change? Doesn't it make no sense that I can configure this on the interface but can't remove it?

**Comment by danischm** [comment]
You can explicitly set the `adminSt` to `enabled` which will re-enable CDP and remove the respective CLI command, but you cannot re-enable it by deleting/destroying the resource, because the DME model does not support that.

**Comment by krzysztofmaciejewskiit** [comment]
Unfortunately this doesn't satisfy me, because the approach we are taking in the project involves removing some code from the TF if we want to remove the configuration on the interface. But ok, we will get around the problem somehow. 
- However, it makes me wonder why, some things have dedicated resources and other things have to be done via nxos_rest? 
- Or, for example, why the LLDP feature is enabled with a dedicated resource, then you have to use nxos_rest to configure LLDP on the interface? 
- In this particular case, I wonder why `lldpIf` I can remove and `cdpIf` not.
Can you explain this to me? I would appreciate it.

**Comment by danischm** [comment]
> - However, it makes me wonder why, some things have dedicated resources and other things have to be done via nxos_rest?
> - Why the LLDP feature is enabled with a dedicated resource, then you have to use nxos_rest to configure LLDP on the interface?
> - Why is there no dedicated resource to run CDP, but there is for LLDP?

**Comment by krzysztofmaciejewskiit** [comment]
Ok thanks. 
I use this visore tool when I need to write my resource.
I wish for myself and you that more resources are created and faster, because TF is very cool.
