### ISSUE TITLE
Error in the documentation for nxos_port_channel_interface_vrf 

### ISSUE THREAD

**Issue by cpiatnit** [CiscoDevNet/terraform-provider-nxos#271]
nxos_port_channel_interface_vrf (Resource)
This resource can manage a port-channel interface VRF association.

API Documentation: [nwRtVrfMbr](https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Routing%20and%20Forwarding/nw:RtVrfMbr/)

the API doc sends the reader to the VRF Membership nw:RtVrfMbr

**Comment by danischm** [comment]
I think this is the right object. The documentation just does not list it as a child of `sys/intf/aggr-[id]`, but if you convert a CLI configuration using NX-OS sandbox, this is what you get.

**Comment by cpiatnit** [comment]
I am Not familiar with the DME model but I thought that an object there would be a match for just a single real world thing.
Apparently not https://pubhub.devnetcloud.com/media/dme-docs-10-2-2/docs/Routing%20and%20Forwarding/nw:RtVrfMbr/

Need to understand how this works (the model)

**Comment by danischm** [comment]
I will close this one if it's ok.
