### ISSUE TITLE
[Terraform] How to remove a VLAN.

### ISSUE THREAD

**Issue by krzysztofmaciejewskiit** [CiscoDevNet/terraform-provider-nxos#280]
I create the VLAN this way. On the device it creates correctly. How do I delete this VLAN now?
```
resource "nxos_rest" "create-vlan" {
  dn         = "sys/bd"
  class_name = "bdEntity"
  children   = [
    {
      rn         = "sys/bd/bd-[vlan-55]"
      class_name = "l2BD"
      content    = {
        name     = "this-is-vlan-55"
        fabEncap = "vlan-55"
      }
    }
  ]
}
```
I do not see how this VLAN can be removed. Even if I remove this resource from the main.tf file this VLAN still remains, I already had a similar case with CDP and LLDP added by nxos_rest.

**Comment by danischm** [comment]
If you define it like this, it attempts to delete the `sys/bd` object, which probably cannot be deleted and therefore also the child object remains in place. There is no need to create or manage the `sys/bd` object, so you should create the VLAN like this:

```terraform
resource "nxos_rest" "create-vlan" {
  dn         = "sys/bd/bd-[vlan-55]"
  class_name = "l2BD"
  content    = {
    name     = "this-is-vlan-55"
    fabEncap = "vlan-55"
  }
}
```

It is always recommended to use individual resources for each object and avoid using "children" if possible as there are some limitations with "children". Though it has to be used under specific circumstances, when both the parent and child object need to be created via a single API call. Also, the `rn` attribute is a relative path and in your example should be `bd-[vlan-55]` and not the full `dn`.

**Comment by krzysztofmaciejewskiit** [comment]
Thanks for your help. I didn't know it would work like that. That's what I missed, it probably solves my other problem with CDP and LLDP.
